apiVersion: v1
kind: Service
metadata:
    name: node-app-service
spec:
    selector:
        app: node-app # Should match node-app-config.yml metadata#name
        tier: backend
    ports:
        - protocol: TCP
            port: 80
            targetPort: node-app-port
    type: LoadBalancer